# Data Retrieval, Cleanup, and Loading

In [11]:
# TODO: For all data retrieval, ensure column names are lowercased and empty spaces are removed

In [12]:
# import pandas as pd

# # import the movie genre,
# movie_data = pd.read_csv('./data/movie_data.csv')
# # TODO: set 'id' as primary key
# # TODO: set 'id', 'title', 'imdb_id' as indexes separately
# movie_data.set_index('id', inplace=True)

# # import the movie_to_persons.csv
# # TODO: set 'movie_id, person_id' as primary key
# # TODO: set 'movie_id', 'person_id', 'imdb_id', 'department' as indexes separately
# # TODO: only bring in the columns 'movie_id', 'person_id', 'imdb_id', 'department' 
# movie_to_persons = pd.read_csv('./data/movie_to_persons.csv')
# movie_to_persons.set_index(['movie_id', 'person_id', 'role'], inplace=True)

# # import the person_data.csv
# # TODO: set 'id' as primary key
# # TODO: set 'id', 'imdb_id', 'name' as indexes separately
# # TODO: bring in all columns
# person_data = pd.read_csv('./data/person_data.csv')
# person_data.set_index('id', inplace=True)

# # import the person_name_race.csv
# # TODO: set 'id' as primary key
# # TODO: set 'id', 'name', 'name_race' as indexes separately
# # TODO: bring in all columns
# person_race = pd.read_csv('./data/person_name_race.csv')
# person_race.set_index('id', inplace=True)

# # import the person_name_race.csv
# # TODO: set 'id' as primary key
# # TODO: set 'id', 'name', 'image_race' as indexes separately
# # TODO: bring in 'id', 'name', 'image_race' columns
# person_race = pd.read_csv('./data/person_name_race.csv')
# person_race.set_index('id', inplace=True)

In [13]:
import pandas as pd

# import the movie genre,
movie_data = pd.read_csv('./data/movie_data.csv')
movie_data.set_index('id', inplace=True) # set 'id' as primary key
movie_data.index.name = 'id'  # Ensuring the index has a name
print(movie_data.head())  # Print the first few rows to check

# import the movie_to_persons.csv
# only bring in the columns 'movie_id', 'person_id', 'imdb_id', 'department' 
movie_to_persons = pd.read_csv('./data/movie_to_persons.csv', usecols=['movie_id', 'person_id', 'imdb_id', 'department'])
movie_to_persons.set_index(['movie_id', 'person_id', 'imdb_id', 'department'], inplace=True) # set 'movie_id, person_id, imdb_id, department' as primary key
print(movie_to_persons.head())  # Print the first few rows to check

# import the person_data.csv
# bring in all columns
person_data = pd.read_csv('./data/person_data.csv')
person_data.set_index('id', inplace=True) # set 'id' as primary key
print(person_data.head())  # Print the first few rows to check

# import the person_name_race.csv
# bring in all columns
person_race_name = pd.read_csv('./data/person_name_race.csv')
person_race_name.set_index('id', inplace=True) # set 'id' as primary key
print(person_race_name.head())  # Print the first few rows to check

# import the person_name_race.csv
# bring in 'id', 'name', 'image_race' columns
person_race_image = pd.read_csv('./data/person_tmdb_image_race.csv', usecols=['id', 'name', 'image_race'])
person_race_image.set_index('id', inplace=True) # set 'id' as primary key
print(person_race_image.head())  # Print the first few rows to check

         genre_Adventure  genre_Comedy  genre_Drama    imdb_id  popularity  \
id
962.0                1.0           1.0          1.0  tt0015864        15.0
44657.0              1.0           NaN          1.0  tt0017743         1.0
82474.0              NaN           NaN          1.0  tt0018379         6.0
28966.0              NaN           NaN          1.0  tt0018578        10.0
85499.0              NaN           NaN          1.0  tt0019553         1.0

         vote_average  vote_count release_date    revenue  \
id
962.0           8.019      1388.0   1925-07-12  4000000.0
44657.0         6.600        16.0   1927-04-29        0.0
82474.0         7.376        86.0   1927-09-10        0.0
28966.0         7.200       233.0   1927-08-12  3600000.0
85499.0         6.800         3.0   1927-10-01        0.0

                                    title  ...  genre_History  genre_Family  \
id                                         ...
962.0                       The Gold Rush  ...            0.0           0.0
44657.0  Chang: A Drama of the Wilderness  ...            0.0           0.0
82474.0                        7th Heaven  ...            0.0           0.0
28966.0                             Wings  ...            0.0           0.0
85499.0              The Way of All Flesh  ...            0.0           0.0

         genre_Western  genre_Thriller  genre_Animation  genre_Fantasy  \
id
962.0              0.0             0.0              0.0            0.0
44657.0            0.0             0.0              0.0            0.0
82474.0            0.0             0.0              0.0            0.0
28966.0            0.0             0.0              0.0            0.0
85499.0            0.0             0.0              0.0            0.0

         genre_Science Fiction  genre_Horror  genre_Mystery  genre_TV Movie
id
962.0                      0.0           0.0            0.0             0.0
44657.0                    0.0           0.0            0.0             0.0
82474.0                    0.0           0.0            0.0             0.0
28966.0                    0.0           0.0            0.0             0.0
85499.0                    0.0           0.0            0.0             0.0

[5 rows x 26 columns]
Empty DataFrame
Columns: []
Index: [(962, 13848, tt0015864, Acting), (962, 14434, tt0015864, Acting), (962, 14435, tt0015864, Acting), (962, 14437, tt0015864, Acting), (962, 14438, tt0015864, Acting)]
         imdb_id             name  gender    birthday    deathday  \
id
13848  nm0000122  Charlie Chaplin       2  1889-04-16  1977-12-25
14434  nm0354913     Georgia Hale       1  1905-06-25  1985-06-07
14435  nm0841501       Mack Swain       2  1876-02-16  1935-08-25
14437  nm0615306       Tom Murray       2  1874-09-08  1935-08-27
14438  nm0074788    Henry Bergman       2  1868-02-23  1946-10-22

                           profile_path
id
13848  /qQZ2qDAyX9aw8KCkj9VZAQLKysK.jpg
14434  /9YxvwUcvGvtjGF7wJXqBWpKRWMH.jpg
14435  /xYULwPUrtqZz50Eaiz3BeZP83iq.jpg
14437  /p80JeuEZeSrRpfmIYH47ARG47C4.jpg
14438  /x41Z1XOGnBg6xnFhxunVQBmcJ36.jpg
                  name name_race
id
13848  Charlie Chaplin     white
14434     Georgia Hale     white
14435       Mack Swain     white
14437       Tom Murray     white
14438    Henry Bergman     white
                  name      image_race
id
13848  Charlie Chaplin           white
14434     Georgia Hale           white
14435       Mack Swain           white
14437       Tom Murray  middle eastern
14438    Henry Bergman           white

In [14]:
import sqlite3

# Establish the database connection
conn = sqlite3.connect('movies_db.sqlite')

# Write the dataframes to tables in the SQLite database
movie_data.to_sql('movie_data', conn, if_exists='replace')
movie_to_persons.to_sql('movie_to_persons', conn, if_exists='replace')
person_data.to_sql('person_data', conn, if_exists='replace')
person_race_name.to_sql('person_race_name', conn, if_exists='replace')
person_race_image.to_sql('person_race_image', conn, if_exists='replace')

# Close the database connection
conn.close()